# Generated by Django 3.2.23 on 2023-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20231112_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': (('ordering',),), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
